[package]
name = "efcl"
version = "0.1.0"
edition = "2021"
license = "MIT"
exclude = ["/test-efcl"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
